### ISSUE TITLE
Deserialization of interface or abstract class

### ISSUE THREAD

**Issue by wangchad** [jsonfx/jsonfx#34]
This is an issue similar to issue #28. When I tried to deserialize to a NET data type with properties which is of an interface or abstract classs, the deserialization will failed. 

If you think about #28 and this issue,  so this is not some rare cases that you won't run into. Especially when you are doing some serious programming, it's common practice to use interfaces. And this issue right now is a big headache for us since we are using interfaces almost everywhere.

**Comment by mckamey** [comment]
Are you proposing a solution or just saying that it doesn't do what you'd like it to? How would you like it to know what your custom interface is backed by? Obviously JsonFx cannot include type information for your custom classes and interfaces, so there must exist a mechanism for it to have attributes which do this mapping.

Highly OO inheritance and deserialization are naturally at odds with one another. It is not uncommon for "serious programming" to use objects which serialize well. One of the big advantages of JsonFx 2.0 was that it added support for dynamic objects which allowed working with deserialized objects without needing to build a large class hierarchy.

Feel free to reopen this issue with a proposal.

In the mean time, this is the block of code which ultimately does the mapping from interface to non-abstract class for you:

https://github.com/jsonfx/jsonfx/blob/master/src/JsonFx/Serialization/TypeCoercionUtility.cs#L721

Somehow that block needs to be able to look at the interface type and be able to figure out the corresponding class.
