### ISSUE TITLE
read/change attribute of root element von XML- or JSON files

### ISSUE THREAD

**Issue by hellboy81** [jsonfx/jsonfx#35]
I need to read and may be change attribute of root element of large XML- or JSON files.

- Is there possible in `jsonfx` to do it w/o parsing whole document?
- Is `jsonfx` suitable for it? As I mentioned this is the only library that supports  both formats in the same engine.

**Comment by mckamey** [comment]
XML read support is somewhat incomplete as I recall but JSON should be solid. JsonFx v2 supports streaming processing which should allow you to process your document without converting all the way to objects. You can just go right from source via tokenizer into tokens, tweak the tokens as they pass, into the generator as source.
