### ISSUE TITLE
Json attributes can't start with dot

### ISSUE THREAD

**Issue by madebysoren** [jsonfx/jsonfx#36]
Hi, 

Thanks for this great library. I am using it in a Unity project connecting to an API, where authentication is controlled. From the API I receive an authentication with an expiry date as well. The expiry date is formatted as ".expires", but JsonFX does not allow that.

EcmaScriptIdentifier.cs, line 148 splits on dot for nesting meaning that I get an ArgumentException: Variable expiression ".expires" is not supported.

I guess there is no reason not to allow properties starting with a dot? The bug probably occurs do to the fact that ".expires" is recognized as a nested property, which it is not. I am not sure where this check is performed, but fixing this nested-check should do the trick I think.

Best,

Søren

**Comment by mckamey** [comment]
Can you give an example of valid input of a property starting with a dot? I'm confused about what you are referring to.

Note that [the method you are talking about](https://github.com/jsonfx/jsonfx/blob/bebad51d6c61188dd348b5951716b863aa6a91cc/src/JsonFx/EcmaScript/EcmaScriptIdentifier.cs#L148) litertally uses the ECMAScript gammar noted in the comment at the top. If your input doesn't follow that grammar then it isn't valid input. So I'm guessing that we might be talking about different things.

**Comment by madebysoren** [comment]
I was referring to this: http://bitoftech.net/2014/07/16/enable-oauth-refresh-tokens-angularjs-app-using-asp-net-web-api-2-owin/ where, if you go to step 5, the response includes a ".issued" and ".expires" attribute. I have however abondoned using these for now.

**Comment by mckamey** [comment]
Please include either a unit test that fails or a snippet of JSON that makes it clear what you are parsing that fails. If a field name contains a dot then it will need to be quoted in either JSON or plain JavaScript. If it does not then it isn't valid, period.

**Comment by madebysoren** [comment]
It's fair. I am using another JSON lib, which works for my needs. So this issue can be closed. I just wanted to let you know that I had troubles using it. Probably because I didn't use it the way it is supposed to. Thanks for the efforts!

**Comment by mckamey** [comment]
It might be the way it is intended. I just need more information. Everything you've reported is vague or requires me to go through a giant multi page doc to find the one snippet of JSON that breaks. Simplify the request and I'd be able to tell you if I can help.

**Comment by madebysoren** [comment]
Here you can see the response:
http://bitoftech.net/wp-content/uploads/2014/07/GenerateRefreshTokenRequest.jpg

You shouldn't spend time on it for my sake, as I don't have the issue anymore. It was just to let you know :)

**Comment by mckamey** [comment]
That screenshot is "pretty printed" (note the tab that's selected) not the raw JSON. If it were that would be invalid JavaScript, let alone JSON.

**Comment by madebysoren** [comment]
Is this invalid?

{".issued":5,".expires":"The current date."}

**Comment by mckamey** [comment]
Nope. That is fine. Strings with dots need to be quoted.

**Comment by madebysoren** [comment]
Alright. Thanks.
